"""
Cross-channel identity linking — infrastructure-owned verification.

A person may have multiple interface identities (WhatsApp, Telegram, etc.).
Linking happens through a one-time verification code generated by infrastructure:

  1. One identity requests linking → infrastructure creates short-lived code
  2. The other identity presents the code → infrastructure verifies
  3. On success, both identities are associated with the same Principal
  4. Expired/used codes cannot be reused

The AI may explain the process to the student, but infrastructure owns verification.
Do not use AI guesses to merge identities.
Do not automatically merge accounts because names or messages look similar.
"""

from __future__ import annotations

import secrets
from datetime import datetime, timezone, timedelta
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from wax.db.models import IdentityLinkChallenge, InterfaceIdentity, Principal
from wax.observability.logging import get_logger

logger = get_logger(__name__)

# Code validity window — short-lived by design
DEFAULT_CODE_TTL_SECONDS = 300  # 5 minutes

# Human-readable hint length cap
_MAX_HINT_LEN = 128


def _generate_code() -> str:
    """Generate an opaque one-time verification code."""
    return secrets.token_hex(8).upper()  # 16 chars


def _generate_hint(principal_display: str | None, pending_channel: str) -> str:
    """Generate a short human-readable hint the AI can relay to the student."""
    channel_label = pending_channel.capitalize()
    if principal_display:
        safe = principal_display[:30]
        return f"Link {channel_label} to {safe}'s account"
    return f"Link your {channel_label} account"


class IdentityLinkService:
    def __init__(self, session: AsyncSession):
        self.session = session

    async def request_link(
        self,
        *,
        principal_id: UUID,
        pending_channel: str,
        pending_external_id: str,
        code_ttl_seconds: int = DEFAULT_CODE_TTL_SECONDS,
        display_hint: str | None = None,
    ) -> IdentityLinkChallenge:
        """
        Create a one-time verification code for linking a second identity.

        The principal must already exist. The pending identity must NOT already
        be linked to a different Principal (no automatic merge of strangers).
        """
        pending_channel = pending_channel.lower().strip()
        pending_external_id = str(pending_external_id).strip()
        if not pending_external_id:
            raise ValueError("missing pending_external_id")

        # Check: pending identity must not already exist and belong to another Principal
        existing = await self._find_identity(pending_channel, pending_external_id)
        if existing and existing.principal_id != principal_id:
            raise ValueError(
                f"pending identity already belongs to another Principal"
            )

        # Generate code and hint
        code = _generate_code()
        hint = display_hint
        if hint is None:
            principal = await self.session.get(Principal, principal_id)
            pd = principal.display_name if principal else None
            hint = _generate_hint(pd, pending_channel)
        if hint and len(hint) > _MAX_HINT_LEN:
            hint = hint[:_MAX_HINT_LEN]

        now = datetime.now(timezone.utc)
        challenge = IdentityLinkChallenge(
            id=uuid4(),
            principal_id=principal_id,
            pending_channel=pending_channel,
            pending_external_id=pending_external_id,
            code=code,
            display_hint=hint,
            status="pending",
            expires_at=now + timedelta(seconds=code_ttl_seconds),
        )
        self.session.add(challenge)
        await self.session.flush()
        logger.info(
            "link_challenge_created",
            challenge_id=str(challenge.id),
            principal_id=str(principal_id),
            pending_channel=pending_channel,
            pending_external_id=pending_external_id,
            hint=hint,
        )
        return challenge

    async def verify_code(
        self,
        *,
        code: str,
        presenting_channel: str,
        presenting_external_id: str,
    ) -> dict[str, Any]:
        """
        Verify a one-time code presented by an identity.

        Returns ok=True on success with linked principal info.
        Returns ok=False with reason on failure.
        """
        code = str(code).strip().upper()
        presenting_channel = presenting_channel.lower().strip()
        presenting_external_id = str(presenting_external_id).strip()

        if not code or not presenting_external_id:
            return {"ok": False, "error": "code_and_identity_required"}

        # Find the challenge by code
        result = await self.session.execute(
            select(IdentityLinkChallenge).where(
                IdentityLinkChallenge.code == code
            )
        )
        challenge = result.scalar_one_or_none()
        if challenge is None:
            logger.warning(
                "link_code_not_found",
                code=code[:8] + "..." if len(code) > 8 else code,
            )
            return {"ok": False, "error": "invalid_code"}

        now = datetime.now(timezone.utc)

        # Check status
        if challenge.status == "used":
            logger.info(
                "link_code_already_used",
                challenge_id=str(challenge.id),
            )
            return {"ok": False, "error": "code_already_used"}

        if challenge.status == "verified":
            logger.info(
                "link_code_already_verified",
                challenge_id=str(challenge.id),
            )
            return {"ok": False, "error": "code_already_verified"}

        if challenge.status == "expired" or (
            challenge.expires_at is not None and challenge.expires_at <= now
        ):
            if challenge.status != "expired":
                challenge.status = "expired"
                await self.session.flush()
            logger.info(
                "link_code_expired",
                challenge_id=str(challenge.id),
            )
            return {"ok": False, "error": "code_expired"}

        # Verify the presenting identity matches the pending identity
        if (
            challenge.pending_channel != presenting_channel
            or challenge.pending_external_id != presenting_external_id
        ):
            logger.warning(
                "link_code_wrong_identity",
                challenge_id=str(challenge.id),
                expected_channel=challenge.pending_channel,
                expected_id=challenge.pending_external_id,
                got_channel=presenting_channel,
                got_id=presenting_external_id,
            )
            return {"ok": False, "error": "code_does_not_match_identity"}

        # All checks passed — verify the link
        return await self._complete_verification(challenge)

    async def _complete_verification(
        self, challenge: IdentityLinkChallenge
    ) -> dict[str, Any]:
        """Internal: mark challenge as used and ensure both identities share a Principal."""
        now = datetime.now(timezone.utc)

        # Check if the pending identity already exists
        existing = await self._find_identity(
            challenge.pending_channel, challenge.pending_external_id
        )

        if existing and existing.principal_id == challenge.principal_id:
            # Already linked — nothing to do, but mark code as used
            challenge.status = "used"
            challenge.consumed_at = now
            await self.session.flush()
            logger.info(
                "link_code_used_identity_already_linked",
                challenge_id=str(challenge.id),
                principal_id=str(challenge.principal_id),
            )
            return {
                "ok": True,
                "already_linked": True,
                "principal_id": str(challenge.principal_id),
                "message": "Identity was already linked to this account.",
            }

        if existing and existing.principal_id != challenge.principal_id:
            # Pending identity belongs to another Principal — refuse
            challenge.status = "expired"
            challenge.error = "pending_identity_belongs_to_other_principal"
            await self.session.flush()
            logger.warning(
                "link_refused_cross_principal",
                challenge_id=str(challenge.id),
                pending_principal=str(existing.principal_id),
                target_principal=str(challenge.principal_id),
            )
            return {
                "ok": False,
                "error": "this_identity_belongs_to_another_account",
                "detail": "The identity you are trying to link is already associated with a different account. Contact support if this is an error.",
            }

        # Create the pending identity if it doesn't exist
        if not existing:
            identity = InterfaceIdentity(
                id=uuid4(),
                principal_id=challenge.principal_id,
                channel=challenge.pending_channel,
                external_id=challenge.pending_external_id,
                is_primary=False,
                metadata_={},
            )
            self.session.add(identity)
            await self.session.flush()
            logger.info(
                "link_identity_created",
                identity_id=str(identity.id),
                principal_id=str(challenge.principal_id),
                channel=challenge.pending_channel,
                external_id=challenge.pending_external_id,
            )
        else:
            # Re-fetch to get the actual row
            existing = await self._find_identity(
                challenge.pending_channel, challenge.pending_external_id
            )
            # Update principal_id if needed (shouldn't happen at this point)
            if existing.principal_id != challenge.principal_id:
                existing.principal_id = challenge.principal_id
                await self.session.flush()

        # Mark challenge as used
        challenge.status = "used"
        challenge.consumed_at = now
        await self.session.flush()

        logger.info(
            "link_verified",
            challenge_id=str(challenge.id),
            principal_id=str(challenge.principal_id),
            channel=challenge.pending_channel,
            external_id=challenge.pending_external_id,
        )

        return {
            "ok": True,
            "already_linked": False,
            "principal_id": str(challenge.principal_id),
            "message": "Your accounts are now linked.",
        }

    async def _find_identity(
        self, channel: str, external_id: str
    ) -> InterfaceIdentity | None:
        """Look up an InterfaceIdentity by channel+external_id."""
        result = await self.session.execute(
            select(InterfaceIdentity).where(
                InterfaceIdentity.channel == channel,
                InterfaceIdentity.external_id == external_id,
            )
        )
        return result.scalar_one_or_none()

    async def get_pending_challenge_for_principal(
        self, principal_id: UUID
    ) -> IdentityLinkChallenge | None:
        """Get the most recent pending challenge for a principal."""
        now = datetime.now(timezone.utc)
        stmt = (
            select(IdentityLinkChallenge)
            .where(
                IdentityLinkChallenge.principal_id == principal_id,
                IdentityLinkChallenge.status == "pending",
                IdentityLinkChallenge.expires_at > now,
            )
            .order_by(IdentityLinkChallenge.created_at.desc())
            .limit(1)
        )
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_challenge_by_code(self, code: str) -> IdentityLinkChallenge | None:
        """Look up a challenge by its code (for status checks, not verification)."""
        result = await self.session.execute(
            select(IdentityLinkChallenge).where(
                IdentityLinkChallenge.code == code.strip().upper()
            )
        )
        return result.scalar_one_or_none()

    async def cleanup_expired(self, limit: int = 100) -> int:
        """Mark expired pending challenges as expired. Returns count."""
        now = datetime.now(timezone.utc)
        stmt = (
            select(IdentityLinkChallenge)
            .where(
                IdentityLinkChallenge.status == "pending",
                IdentityLinkChallenge.expires_at <= now,
            )
            .order_by(IdentityLinkChallenge.expires_at.asc())
            .limit(limit)
            .with_for_update(skip_locked=True)
        )
        result = await self.session.execute(stmt)
        rows = list(result.scalars().all())
        for c in rows:
            c.status = "expired"
        if rows:
            await self.session.flush()
        logger.info("link_challenges_cleaned", count=len(rows))
        return len(rows)
